"use client";

import Link from "next/link";
import { useState } from "react";
import { Baby, Droplets, HandHeart, PackageOpen, ShoppingBasket, Truck, Users } from "lucide-react";
import { Card } from "./site-components";

const swishUrl = "https://app.swish.nu/1/p/sw/?sw=0707881017";
const stats = [
  [Users, "4300+", "Människor hjälpta"], [Baby, "522", "Förpackningar modersmjölkersättning"],
  [Droplets, "85,000+", "Liter färskt vatten distribuerat"], [HandHeart, "38", "Projekt genomförda"],
] as const;

export default function Home() {
  const [amount, setAmount] = useState("250");
  return <>
    <section className="hero"><div className="hero-overlay" /><div className="container hero-copy"><h1>Gaza ska leva</h1><p>Vi på Sanad är inte bara en organisation, utan ett community av eldsjälar engagerade för Gazas familjer och framtid. Gaza behöver vår handling, inte våra tårar.</p><div className="hero-buttons"><Link href="/om-oss" className="button glass">Om Oss</Link><Link href="/kontakt" className="button glass">Bli medlem</Link></div></div></section>
    <section className="quick-donate"><div className="container quick-inner"><div><strong>Din donation – vårt ansvar</strong><span>Välj belopp eller ange eget</span></div><div className="amount-row">{[100,250,500,1000].map(v => <button className={amount === String(v) ? "selected" : ""} key={v} onClick={() => setAmount(String(v))}>{v}kr</button>)}<input aria-label="Eget belopp" type="number" min="10" value={amount} onChange={e => setAmount(e.target.value)} /><a className="button swish" href={swishUrl} target="_blank"><img src="/swish.jpeg" alt="" />Swisha nu</a></div></div></section>
    <section className="section"><div className="container"><div className="section-heading"><h2>Vad vi åstadkommit hittills</h2><p>Tack vare våra givare har vi kunnat göra en verklig skillnad för människor i Gaza.</p></div><div className="stats">{stats.map(([Icon, number, label]) => <Card key={label}><div className="icon-circle"><Icon /></div><strong>{number}</strong><span>{label}</span></Card>)}</div></div></section>
    <section className="section muted"><div className="container split"><div><h2>Hur används din donation?</h2><p>Gaza är vår tids största humanitära kris. Barnfamiljer lever i rädsla av bomber, hunger, törst, sjukdomar, kyla och hetta. Ca 10-15% av fastigheter står kvar, vilket innebär att miljoner bor i tält och tusentals ute på gatan. Utan tillgång till vatten, mat eller sjukvård är det vårt ansvar att svara på deras nödrop. Ca 90% av människorna i Gaza överlever enbart tack vare donationer från utlandet.</p><p>Vi finns på plats för att leverera humanitärt stöd i form av mat, vatten, modersmjölkersättning, tält och varma kläder till familjer i behov. Vi fokuserar på långsiktig påverkan genom att utbilda och sysselsätta änkor med barn och kvinnor med skadade män.</p><p><strong>Tillsammans gör vi en stor skillnad. Vi på Sanad hjälper dig att förvandla din omtanke till handling, precis det Gaza behöver.</strong></p><Link href="/donera" className="button">Donera nu</Link></div><img className="team-image" src="/about.jpg" alt="Sanads team i Gaza" /></div></section>
    <section className="section muted journey"><div className="narrow"><div className="section-heading"><h2>Från din hand till deras</h2><p>Följ resan från din donation till de familjer som får hjälp. Varje steg är transparent och effektivt.</p></div><div className="timeline">{[[HandHeart,"Du bidrar","Du bidrar genom Swish! Stripe och Donorbox kommer snart! Ditt stöd är starten på hela processen."],[PackageOpen,"Vi samlar in","Alla donationer samlas och skickas till Gaza där våra medarbetare planerar inköp baserat på aktuella behov på plats."],[ShoppingBasket,"Vi köper och paketerar","Mat, mediciner, kläder och annat nödvändigt köps in och paketeras för transport."],[Truck,"Vi distribuerar","Våra medarbetare på plats i Gaza distribuerar stödet och ser till att familjerna får hjälp."]].map(([Icon,title,text], i) => <div className={`timeline-item ${i%2 ? "right" : ""}`} key={title as string}><div className="timeline-icon"><Icon /></div><Card><h3>{title as string}</h3><p>{text as string}</p></Card></div>)}</div><div className="center"><p>Hela processen tar i genomsnitt 2-3 veckor från din donation till distribution.</p><Link href="/donera" className="button">Starta resan idag</Link></div></div></section>
    <section className="section"><div className="container"><div className="section-heading"><h2>Våra berättelser</h2><p>Möt några av de familjer vars liv har förändrats tack vare ditt stöd. Deras berättelser är vårt ”varför”.</p></div><h3 className="subheading">Från fältet</h3><div className="story-grid">{[["/field-food.jpg","Distribution av mat och vatten","Barn får tillgång till modersmjölkersättning och andra nödvändiga livsmedel genom våra distributionscenter."],["/field-team.jpg","Vårt team på plats","Våra medarbetare arbetar dagligen för att se till att hjälpen når fram till familjerna som behöver det mest."]].map(([src,title,text]) => <Card className="story" key={title}><img src={src} alt={title} /><div><h3>{title}</h3><p>{text}</p></div></Card>)}</div><h3 className="subheading video-title">Videoberättelser</h3><div className="video-grid">{[["/story-1.mp4","Vårt arbete på plats","Se hur vi distribuerar mat och vatten till familjerna i Gaza."],["/story-2.mp4","Stöd till familjer","Vårt team arbetar dagligen för att hjälpa de som behöver det mest."],["/story-3.mp4","Från fältet","Autentiska bilder från vårt arbete i Gaza."]].map(([src,title,text]) => <Card className="story" key={title}><video src={src} controls preload="metadata" /><div><h3>{title}</h3><p>{text}</p></div></Card>)}</div></div></section>
    <section className="section muted"><div className="container"><div className="section-heading"><h2>Våra sponsorer</h2><p>Tack till våra partners som gör vårt arbete möjligt</p></div><div className="sponsors"><Sponsor href="https://www.joart.io" image="/sponsor-joart.png" name="JOART SYSTEMS" /><Sponsor href="https://pureimaan.se" image="/sponsor-pureiman.png" name="Pureimaan.se" /><Sponsor href="https://albymoske.se/" name="Alby islamiskt center" /></div><div className="center"><Link href="/sponsorer" className="button outline">Se alla sponsorer</Link></div></div></section>
  </>;
}

function Sponsor({ href, image, name }: { href: string; image?: string; name: string }) { return <a href={href} target="_blank" className="sponsor-card">{image ? <img src={image} alt={name} /> : <strong>{name}</strong>}</a> }
